from functions import *

launch_website()
click_element_by_xpath(sign_in_link, "Log In")
enter_text_by_xpath(email_create, email)
click_element_by_xpath(button_create, "Create account")
radio_button(gender_input)
enter_text_by_xpath(first_name_input, name)
enter_text_by_xpath(last_name_input, last_name)
enter_text_by_xpath(password_input, pwd)
select(day_sel, "8")
select(month_sel, "10")
select(year_sel, "1991")
enter_text_by_xpath(address_input, address)
enter_text_by_xpath(city_input, city)
select(state_select, "32")
enter_text_by_xpath(zip_input, zip)
select(country_select, "21")
enter_text_by_xpath(mobile_phone_input, phone)
click_element_by_xpath(register_button, "Registration")
account_ready(main_path)
sign_out(sign_out_link)
close()